//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated manually for VS Code use.
//------------------------------------------------------------------------------
namespace Editor.App.Properties
{
    [global::System.Runtime.CompilerServices.CompilerGenerated]
    [global::System.CodeDom.Compiler.GeneratedCode("Manual", "1.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {
        private static Settings defaultInstance =
            ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default => defaultInstance;

        [global::System.Configuration.UserScopedSetting]
        [global::System.Diagnostics.DebuggerNonUserCode]
        [global::System.Configuration.DefaultSettingValue("Dark")]
        public string Theme
        {
            get => ((string)this["Theme"]);
            set => this["Theme"] = value;
        }
    }
}
